### ISSUE TITLE
[Bug] pipeline agent policy drift

### ISSUE THREAD

**Issue by Terilia** [elastic/terraform-provider-elasticstack#749] opened 2024-09-02 08:58 UTC
**Describe the bug**
I am experiencing unintended behavior with Terraform pipelines. Whenever the pipelines are applied, a new version of the policy is generated. This leads to policy updates being pushed to all agents, causing delays in log processing. This behavior might be due to drifting, which results in frequent and unnecessary policy updates even if no substantial changes were made.

**To Reproduce**
1. TF configuration used:
```hcl

    resource "elasticstack_fleet_integration" "cf_push" {
  name    = "cloudflare_logpush"
  version = "1.21.0"
  force   = true
}

// An agent policy to hold the integration policy.
resource "elasticstack_fleet_agent_policy" "cf_push" {
  name            = "cloudflare_logpush-ap"
  namespace       = "default"
  description     = "cloudflare_logpush"
  monitor_logs    = true
  monitor_metrics = true
  skip_destroy    = false
}

// The associated enrollment token.
data "elasticstack_fleet_enrollment_tokens" "cf_push" {
  policy_id = elasticstack_fleet_agent_policy.cf_push.policy_id
}

// The integration policy.
resource "elasticstack_fleet_integration_policy" "cf_push" {
  name                = "cloudflare_logpush"
  namespace           = "default"
  description         = "Cloudflare logs integration 1999920 IAC"
  agent_policy_id     = elasticstack_fleet_agent_policy.cf_push.policy_id
  integration_name    = elasticstack_fleet_integration.cf_push.name
  integration_version = elasticstack_fleet_integration.cf_push.version

  dynamic "input" {
    for_each = local.cf_push_inputs
    content {
      enabled      = input.value.enabled
      input_id     = input.value.input_id
      vars_json    = input.value.vars_json
      streams_json = input.value.streams_json
    }
  }
}

locals {

  agent_stream_settings = yamldecode(templatefile(
    "${path.module}/cf_logpush_stream.tftpl",
    {
      config        = var.cloudflareLPJob.logpushJobs
      port          = var.cloudflareLPJob.common.port
      prefix        = var.cloudflareLPJob.common.prefix
      keep_original = var.cloudflareLPJob.common.keepOriginal
      tags          = var.cloudflareLPJob.common.tags
    }
    )
  )

  cf_push_inputs = {
    cloudflare-http_endpoint = {
      enabled  = true
      input_id = "cloudflare-http_endpoint"
      vars_json = jsonencode({
        "listen_address" : "0.0.0.0",
        "secret_header" : "${var.agentAuthKey}",
        "secret_value" : "${var.agentAuthValue}",
        "ssl" : "{\"certificate\":\"/etc/ssl/certs/logpush/server.crt\",\"certificate_authorities\":\"/etc/ssl/certs/root.pem\",\"client_authentication\":\"none\",\"key\":\"/etc/ssl/certs/logpush/server.key\"}"
        }
      )
      streams_json = jsonencode(local.agent_stream_settings)
    },
    cloudflare-aws-s3 = {
      enabled      = false
      input_id     = "cloudflare-aws-s3"
      streams_json = "masked_value"
      vars_json    = "masked_value"
    },
    cloudflare-gcs = {
      enabled      = false
      input_id     = "cloudflare-gcs"
      streams_json = "masked_value"
      vars_json    = "masked_value"
    }
  }
}


variable "agentAuthKey" {
  description = "Elastic Agent Cloudflare API auth header key. Supplied as an environmental variable"
}
variable "agentAuthValue" {
  description = "Elastic Agent Cloudflare API auth header value. Supplied as an environmental variable"
}
variable "cloudflareSettings" {
  type = object({
  })
  default = {
  }
  description = "Cloudflare settings such as agent base config"
}

variable "cloudflareLPJob" {
  type = object({
    common = object({
      port         = number
      prefix       = string
      tags         = string
      keepOriginal = bool
    })
    cfSettings = object({
      agentFQDN    = string
      parameters   = string
      cfNamePrefix = string
    })
    logpushJobs = list(object({
      name         = string
      logpull_opts = string
      datasetName  = string
      zone_id      = string
      account_id   = string
      })
    )
  })

  description = "Object to define Logpush jobs, expose it via elasticsearch agent adn setup logpush jobs."
}
```
2. TF operations to execute to get the error: 
    - `terraform plan`
    - `terraform apply`
3. See the error in the output:
    - Every application of the Terraform pipeline generates a new policy version.
    - All agents receive the updated policy, resulting in delays in log processing.

**Expected behavior**
Applying the Terraform pipeline should be idempotent. Only necessary updates should be made without generating new policy versions if not required. Agents should not experience unnecessary policy updates or delays in log processing.

**Screenshots**

![Image](https://github.com/user-attachments/assets/2bcc310e-0369-41a2-bb90-dd69eeafa2f5)

**Versions (please complete the following information):**
- Provider version: 0.11.4

**Additional context**
I believe that drifting may be causing this issue. I'm looking for an idempotent solution to ensure that only necessary changes trigger policy updates. This will help improve policy version control and reduce the delays in log processing for the agents.

**Comment by tobio** [comment] 2024-09-11 08:45
Closing as a duplicate of https://github.com/elastic/terraform-provider-elasticstack/issues/689

**Closed** 2024-09-11 08:45 UTC
Labels: bug
