### ISSUE TITLE
[Bug] unexpected new value: .ca_trusted_fingerprint: was null, but now cty.StringVal("")

### ISSUE THREAD

**Issue by kaykhan** [elastic/terraform-provider-elasticstack#931] opened 2024-11-26 09:52 UTC
**Describe the bug**

Updating elasticstack_fleet_output seems to break with the following error:

> elasticstack_fleet_output.elasticsearch_output: Modifying... [id=8f6b6c2a-1d63-4acd-bb2d-ea653dd53168]
> ╷
> │ Error: Provider produced inconsistent result after apply
> │
> │ When applying changes to elasticstack_fleet_output.elasticsearch_output, provider "provider[\"registry.terraform.io/elastic/elasticstack\"]" produced
> │ an unexpected new value: .ca_trusted_fingerprint: was null, but now cty.StringVal("").
> │
> │ This is a bug in the provider, which should be reported in the provider's own issue tracker.
> 
> 

**To Reproduce**

- update hosts array with a new entry
```
resource "elasticstack_fleet_output" "elasticsearch_output" {
  name                 = "elasticsearch"
  type                 = "elasticsearch"
  config_yaml          = yamlencode({})
  default_integrations = true
  default_monitoring   = true
  hosts = [
    "https://${data.terraform_remote_state.eck_elasticsearch.outputs.elasticsearch_name}-es-http.elastic-system.svc:9200",
    "https://elasticsearch.acme.test.com:443" # added
  ]
  depends_on = [
    helm_release.fleet_server
  ]
}
```

**Expected behavior**

Expect for the fleet_output to be updated

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations. **Please ensure you redact any base64 encoded credentials from your output**. 
eg
```
[DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Authorization: Basic xxxxx==
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/088cb734-3356-4e6b-876a-57e09ee43f9c)

**Versions (please complete the following information):**
 - OS: [e.g. Linux]: Ubuntu
 - Terraform Version [e.g. 1.0.0]
 - Provider version [e.g. v0.1.0]: v0.11.11
 - Elasticsearch Version [e.g. 7.16.0]: 8.16.1

**Additional context**

I updated the fleet server from 8.15.4 to 8.16.1 at the same time

**Comment by tobio** [comment] 2024-11-27 21:48
Thanks @kaykhan, closing this one as a duplicate of #836. We've had trouble reproducing this, hopefully we can narrow this down and get a fix with your details 👍

**Closed by tobio** 2024-11-27 21:48 UTC
Labels: bug
