### ISSUE TITLE
[Bug] Can not create data_view

### ISSUE THREAD

**Issue by jasiura** [elastic/terraform-provider-elasticstack#561] opened 2024-02-06 16:53 UTC
**Describe the bug**
Creation of new data_view is not possible

**To Reproduce**
1. TF configuration used:

```terraform {
  required_providers {
    elasticstack = {
      source = "elastic/elasticstack"
      version = "0.11.0"
    }
  }

  required_version = ">= 0.13.7"
}

provider "elasticstack" {
  elasticsearch {
    api_key   = var.api_key_base64
    endpoints = [var.elasticUrl]
  }
  kibana {
      endpoints = [var.kibanaUrl]
    }
  }

resource "elasticstack_kibana_data_view" "dataview-example" {
  space_id = "example"
  data_view = {
    name = "metricbeat"
    title = "metricbeat-*"
    time_field_name = "@timestamp"
  }
}
```
2. TF operations to execute to get the error `terraform apply`
3. See the error in the output:

`Failed with:
│ {"statusCode":401,"error":"Unauthorized","message":"[security_exception\n\tRoot
│ causes:\n\t\tsecurity_exception: unable to authenticate user [] for REST
│ request [/_security/_authenticate]]: unable to authenticate user [] for
│ REST request [/_security/_authenticate]"}`

**Expected behavior**
Data view should be created

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations. 
eg
```
2024-02-06T16:36:34.877Z [INFO]  Starting apply for elasticstack_kibana_data_view.dataview-example
2024-02-06T16:36:34.877Z [DEBUG] skipping FixUpBlockAttrs
2024-02-06T16:36:34.877Z [DEBUG] elasticstack_kibana_data_view.dataview-example: applying the planned Create change
2024-02-06T16:36:34.877Z [TRACE] GRPCProvider.v6: ApplyResourceChange
2024-02-06T16:36:34.878Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Received request: tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:844 @module=sdk.proto tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_proto_version=6.4 timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.878Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Sending request downstream: tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_resource_type=elasticstack_kibana_data_view @caller=github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tf6serverlogging/downstream_request.go:20 @module=sdk.proto tf_proto_version=6.4 tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_rpc=ApplyResourceChange timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.878Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: calling downstream server: tf_mux_provider=*proto6server.Server tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-mux@v0.12.0/internal/logging/mux.go:19 @module=sdk.mux timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.878Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Checking ResourceTypes lock: @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server.go:396 tf_mux_provider=*proto6server.Server tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_rpc=ApplyResourceChange @module=sdk.framework tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_resource_type=elasticstack_kibana_data_view timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: ApplyResourceChange received no PriorState, running CreateResource: tf_mux_provider=*proto6server.Server tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:45 @module=sdk.framework tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Resource implements ResourceWithConfigure: @module=sdk.framework tf_mux_provider=*proto6server.Server tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:47 tf_provider_addr=registry.terraform.io/elastic/elasticstack timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Calling provider defined Resource Configure: @module=sdk.framework @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:54 tf_mux_provider=*proto6server.Server tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Called provider defined Resource Configure: @module=sdk.framework tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:56 tf_mux_provider=*proto6server.Server tf_provider_addr=registry.terraform.io/elastic/elasticstack timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Calling provider defined Resource Create: tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_mux_provider=*proto6server.Server tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_resource_type=elasticstack_kibana_data_view @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:100 @module=sdk.framework tf_rpc=ApplyResourceChange timestamp=2024-02-06T16:36:34.878Z
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 2024/02/06 16:36:34 
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: POST /api/data_views/data_view HTTP/1.1
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Host: xxxxxx
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: User-Agent: elasticstack-terraform-provider/0.11.0
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Length: 134
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Accept: application/json
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Authorization: Basic xxxx
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Type: application/json
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: kbn-xsrf: true
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Accept-Encoding: gzip
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: {"data_view":{"allowNoIndex":false,"id":"","name":"metricbeat","timeFieldName":"@timestamp","title":"metricbeat-*"},"override":false}
2024-02-06T16:36:34.879Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 2024/02/06 16:36:34 
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: HTTP/2.0 401 Unauthorized
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Length: 266
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Cache-Control: private, no-cache, no-store, must-revalidate
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Security-Policy: script-src 'report-sample' 'self'; worker-src 'report-sample' 'self' blob:; style-src 'report-sample' 'self' 'unsafe-inline'; report-to violations-endpoint
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Type: application/json; charset=utf-8
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Cross-Origin-Opener-Policy: same-origin
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Date: Tue, 06 Feb 2024 16:36:34 GMT
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Kbn-License-Sig: xxxx
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Kbn-Name: instance-0000000075 - UI
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Permissions-Policy: camera=(), display-capture=(), fullscreen=(self), geolocation=(), microphone=(), web-share=()
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Referrer-Policy: no-referrer-when-downgrade
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Reporting-Endpoints: violations-endpoint="xxxx/internal/security/analytics/_record_violations"
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Cloud-Request-Id: xxxx
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Content-Type-Options: nosniff
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Cluster: xxxx
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Instance: instance-0000000075
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 
2024-02-06T16:36:34.913Z [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: {"statusCode":401,"error":"Unauthorized","message":"[security_exception\n\tRoot causes:\n\t\tsecurity_exception: unable to authenticate user [] for REST request [/_security/_authenticate]]: unable to authenticate user [] for REST request [/_security/_authenticate]"}
2024-02-06T16:36:34.913Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Called provider defined Resource Create: tf_mux_provider=*proto6server.Server tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:102 @module=sdk.framework timestamp=2024-02-06T16:36:34.913Z
2024-02-06T16:36:34.914Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Received downstream response: @module=sdk.proto tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tf6serverlogging/downstream_request.go:40 tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_req_duration_ms=35 tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view diagnostic_error_count=1 diagnostic_warning_count=0 timestamp=2024-02-06T16:36:34.913Z
2024-02-06T16:36:34.914Z [ERROR] provider.terraform-provider-elasticstack_v0.11.0: Response contains error diagnostic: diagnostic_severity=ERROR tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_resource_type=elasticstack_kibana_data_view tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_detail="Failed with: {"statusCode":401,"error":"Unauthorized","message":"[security_exception\n\tRoot causes:\n\t\tsecurity_exception: unable to authenticate user [] for REST request [/_security/_authenticate]]: unable to authenticate user [] for REST request [/_security/_authenticate]"}" diagnostic_summary="Unable to create data view" timestamp=2024-02-06T16:36:34.913Z
2024-02-06T16:36:34.914Z [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Served request: tf_resource_type=elasticstack_kibana_data_view tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/elastic/elasticstack @caller=github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:870 @module=sdk.proto tf_req_id=cacc8fa5-ab5b-c5b5-de8f-3997ec43abac tf_rpc=ApplyResourceChange timestamp=2024-02-06T16:36:34.913Z
2024-02-06T16:36:34.914Z [TRACE] maybeTainted: elasticstack_kibana_data_view.dataview-example encountered an error during creation, so it is now marked as tainted
2024-02-06T16:36:34.914Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for elasticstack_kibana_data_view.dataview-example
2024-02-06T16:36:34.914Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for elasticstack_kibana_data_view.dataview-example
2024-02-06T16:36:34.914Z [TRACE] evalApplyProvisioners: elasticstack_kibana_data_view.dataview-example is tainted, so skipping provisioning
2024-02-06T16:36:34.914Z [TRACE] maybeTainted: elasticstack_kibana_data_view.dataview-example was already tainted, so nothing to do
2024-02-06T16:36:34.914Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for elasticstack_kibana_data_view.dataview-example
2024-02-06T16:36:34.914Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for elasticstack_kibana_data_view.dataview-example
2024-02-06T16:36:34.914Z [ERROR] vertex "elasticstack_kibana_data_view.dataview-example" error: Unable to create data view
2024-02-06T16:36:34.914Z [TRACE] vertex "elasticstack_kibana_data_view.dataview-example": visit complete, with errors
2024-02-06T16:36:34.914Z [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/elastic/elasticstack\"] (close)" errored, so skipping
2024-02-06T16:36:34.914Z [TRACE] dag/walk: upstream of "root" errored, so skipping
2024-02-06T16:36:35.133Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2024-02-06T16:36:35.134Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/elastic/elasticstack/0.11.0/linux_amd64/terraform-provider-elasticstack_v0.11.0 pid=82
2024-02-06T16:36:35.134Z [DEBUG] provider: plugin exited
Operation failed: failed running terraform apply (exit 1)
```

**Versions (please complete the following information):**
 - OS: MacOS
 - Terraform Version: 1.1.9
 - Provider version 0.11.0
 - Elasticsearch Version 8.12.0

**Additional context**
When i try to get cluster info with this same credentials that was possible.
I tried use the same api_key with curl command to create data_view and that works.

In terraform logs is information about Authorization: "Authorization: Basic xxx", when i used curl command i used "Authorization: ApiKey xxxx" shouldn't be the same?

**Comment by tobio** [comment] 2024-02-06 22:35
Thanks for the report, this one's fixed in main, and will be part of the next release which should be out in the next weeks. 

Duplicate of https://github.com/elastic/terraform-provider-elasticstack/issues/529
Fixed by https://github.com/elastic/terraform-provider-elasticstack/pull/549

**Closed by tobio** 2024-02-06 22:35 UTC
Labels: bug
