### ISSUE TITLE
[Bug] provider cannot auth w/ PWs containing irregular chars

### ISSUE THREAD

**Issue by neckenth** [elastic/terraform-provider-elasticstack#111] opened 2022-05-26 18:26 UTC
**Describe the bug**
When creating a new Elasticsearch user via ElasticCloud UI, passwords with irregular characters are accepted. When using a password with irregular characters as the password for the `elastic/elasticstack` provider, cluster authentication fails. Perhaps the set of irregular characters are those that require URL encoding. ([MDN docs here](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding)). `&` was the culprit for me.

The solution is to change the password to only include regular characters. When you do so in the ElasticCloud web app, however, this creates a need to `terraform destroy` the elasticstack user and associated resources or `terraform rm` those resources from the Terraform state. Otherwise, the bad password _continues_ to get used to try to connect to your ElasticSearch cluster by the `elastic/elasticstack` provider before the Terraform process arrives at using the the good password to authenticate the user.

For the sake of reproducing the issue, the password used was `eM&oM9Mh$FHN$#bo` (rotated and no longer in use, obviously)

**To Reproduce**
1. [config] In the ElasticCloud UI, create a new User (or update an existing User) and set the password to one that includes an `&`.
2. [config] In your `provider.tf` file, set the `elasticsearch` argument in the `elasticstack` provider object to use these new credentials:
```
provider "elasticstack" {
  elasticsearch {
    username  = <username>
    password  = <pw_w_irregular_chars>
    endpoints = [...]
  }
}
```
3. [operations] `terraform apply`
4. [error]
```
Failed with: {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [<username>] for REST request
│ [/<index_name>?flat_settings=true]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer
│ realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate user [<username>] for REST request
│ [/<index_name>?flat_settings=true]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer
│ realm=\"security\"","ApiKey"]}},"status":401}
```
**Expected behavior**
It is expected that the same password requirements would be used by both the ElasticCloud web app and the `elastic/elasticstack` provider. Any characters accepted in passwords by ElasticCloud should be supported by the `elastic/elasticstack` provider.

**Debug output**
N/A - Running the debug output doesn't include any requests or logs pertaining to the `elastic/elasticstack` provider surrounding this error. Only the Terraform error (as seen above) appears in the output.

**Versions:**
 - OS: macOS Monterey v. 12.2.1
 - Terraform Version: v1.1.7
 - Provider version: 0.3.3
 - Elasticsearch Version: 7.16.3

**Comment by tobio** [comment] 2022-10-09 23:42
I  can't reproduce this with the provided password, and there's nothing in the provider which treats the password as anything but a string parameter used by the [go-elasticsearch](https://github.com/elastic/go-elasticsearch) client. 

For clarity, I have hard coded the credentials:

```
provider "elasticstack" {
  elasticsearch {
    username  = "terraform"
    password  = "eM&oM9Mh$FHN$#bo"
    endpoints = [ec_deployment.deployment.elasticsearch[0].https_endpoint]
  }
}
```

I'm closing this for now, happy to dig into this further if anyone has a current reproduction, including how those credentials are provided to Terraform. For example `export TF_VAR_ELASTIC_PASSWORD=eM&oM9Mh$FHN$#bo` is going to be subject to shell substitutions.

**Closed** 2022-10-09 23:42 UTC
Labels: bug
