### ISSUE TITLE
[Feature] Add JWT Bearer Token Authentication to the Provider

### ISSUE THREAD

**Issue by SquareShark** [elastic/terraform-provider-elasticstack#373] opened 2023-06-30 15:38 UTC
With 8.8.0s update to GA release [patch notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.8.0.html) or the [ticket is here](https://github.com/elastic/elasticsearch/pull/95398) 

Pretty please, can we add in a new schema for taking in JWT tokens and then just altering the headers to pass that through instead of username and password/API keys?

**Comment by SquareShark** [comment] 2023-10-11 12:57
Hey, i have had a play around with this (first ever time using GO and with public Github repos), does this look good?
https://github.com/elastic/terraform-provider-elasticstack/compare/main...SquareShark:terraform-provider-elasticstack-jwt:jwt_support

I have tested it and it does work, allows me to authenticate into Elasticsearch deployments to create objects, never touched the Kibana side of things but hopefully this can help maybe?

**Comment by tobio** [comment] 2023-10-16 05:43
> does this look good?

Definitely a good starting point, we'd want to support environment overrides etc here as well.

> I have tested it and it does work

Looking at your branch it doesn't look like you're setting the [shared secret](https://www.elastic.co/guide/en/elasticsearch/reference/current/jwt-auth-realm.html#hmac-oidc-example-request-headers) (`ES-Client-Authentication` header) anywhere. Am I missing something here?  

Open a PR with your changes and we can get them merged in :)

**Comment by SquareShark** [comment] 2023-11-15 15:28
@tobio I have created a PR for it, I did sign the agreement but not sure how to kick off a rebuild for it.. Please let me know what you think, Pretty new to this so sorry if i have made some beginner mistakes. https://github.com/elastic/terraform-provider-elasticstack/pull/481

**Comment by tobio** [comment] 2023-11-19 22:04
> I did sign the agreement but not sure how to kick off a rebuild for it..

Thanks for this, I can see you've signed it but the checker isn't still failing. I _think_ it's because the email you've signed with isn't published as part of your GH profile and so the commits are showing as `Author: SquareShark <115224129+SquareShark@users.noreply.github.com>`. I'll try and verify that's the cause internally, if you're happy publishing that email address we can test it out here as well.

**Comment by SquareShark** [comment] 2023-11-20 17:16
So if i change my email to public will it fix the issue?

**Comment by tobio** [comment] 2023-11-21 01:42
I think so, we may need to rewrite the author on these commits as well after that. I haven't heard back, so I'm not 100% sure that's the issue but definitely worth a shot if you're happy with it.

**Closed** 2023-12-08 08:10 UTC
Labels: enhancement
