### ISSUE TITLE
[Bug] elasticstack_fleet_integration_policy render consistent diff for policy secret

### ISSUE THREAD

**Issue by Holi0317** [elastic/terraform-provider-elasticstack#689] opened 2024-07-26 18:39 UTC
**Describe the bug**

When configuring [policy secret](https://www.elastic.co/guide/en/fleet/8.14/agent-policy.html#agent-policy-secret-values) via integration policy resource, the provider and terraform always renders a diff even though the value is not changed.

I'm trying to configure the universal profiler integration.

**To Reproduce**

```terraform
resource "elasticstack_fleet_integration_policy" "profiling" {
  name      = "profiling"

  agent_policy_id     = elasticstack_fleet_agent_policy.this.policy_id
  integration_name    = data.elasticstack_fleet_integration.profiling.name
  integration_version = data.elasticstack_fleet_integration.profiling.version

  input {
    input_id     = "universal_profiling_agent-pf-host-agent"
    streams_json = jsonencode({})
    vars_json = jsonencode({
      "profiler.collector"    = "cloud-es.io"
      "profiler.secret_token" = "Hunter2"
      "profiler.disable_tls"  = false
    })
  }
}
```

Apply once, then make a plan.

**Expected behavior**
There should not be any diff in the second plan.

**Versions (please complete the following information):**
 - OS: MacOS
 - Terraform Version: v1.7.5
 - Provider version 0.1.4
 - Elasticsearch Version 8.14.3

**Comment by Holi0317** [comment] 2024-07-26 18:39
CC @Kushmaro. Maybe related to #617.

**Comment by breml** [comment] 2024-08-09 07:23
We are affected by this issue as well. In our case, it is with the Azure Logs integration where the `connection_string` and `storage_account_key` values in the `vars_json` are now replaced with something like:

```json
{
  id = "oJo..."
  isSecretRef = true
}
```

when the old value was just a string.

Now it is unclear how to continue, since executing our Terraform would overwrite the referrences to the secret values (and we don't know, if this is safe to do), but on the other hand we do not have a way to manage and import the secret values either.

**Comment by breml** [comment] 2024-08-23 12:02
I looked at this problem again and I wonder, what the plan is at Elastic on this.

Based on [secrets.md](https://github.com/elastic/kibana/blob/08f0ed0168aa41179d2d5d31d4243b1b06b161ab/x-pack/plugins/fleet/dev_docs/secrets.md) the idea is to prevent Kibana and Fleet users from having read access to the secrets, that are part of the fleet integrations. So far, so good. But now it looks like there is no API left that could be used by e.g. Terraform to manage this as Iaas. 

I would be thankful, if someone from Elastic could elaborate on this problem and provide some more details on the plan forward and if possible on a timeline.

**Comment by tobio** [comment] 2024-08-26 07:25
> provide some more details on the plan forward

To be clear, there's no definitive plan here at the moment. This is just based on similar issues in other resources. Some options though:

1. Having write only attributes. For example API keys will not detect 'drift' in the actual API Key, it's read during the create request and assumed to be static as it's not returned during subsequent read operations. Technically the key could be deleted and recreated outside of Terraform and we wouldn't detect the change. This works well for concrete attributes (i.e not part of a homogeneous JSON blob, which we're not dealing with in this case. 
2. [`lifecycle.ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes). This obviously isn't ideal since Terraform wouldn't correct any legitimate drift within `vars_json`. 

In the providers current state, we can't easily apply 1 in this case since there's just a JSON bag of properties that is used for a variety of input types, and 2 is far from ideal for practitioners. To properly address this issue, we'd need to make some changes to how this resource is implemented, but that's a larger chunk of work and something that will likely be addressed as part of https://github.com/elastic/terraform-provider-elasticstack/issues/617. There's no timeframe on either of these issues at the moment sorry.

**Comment by breml** [comment] 2024-08-30 05:48
@tobio Thanks for your reply. The current situation is really unfortunate for us. We have a paid subscription of Elasticsearch in the Elastic Cloud. We use terraform to manage the Elastic Cloud deployment as well as the configuration of Elasticsearch including the Fleet integrations.

This worked until we updated our Elasticsearch instance to 8.14.3 and now, we are basically in a dead end, since we can not update our Terraform configuration to compensate for the drift cause by the updates of the fleet integrations, which became necessary due to the update of Elasticsearch.
Already before this change, it was not simple to keep the drift under control, which is caused by the updates of the Fleet integrations. But we managed to do so using [tfreveal](https://github.com/breml/tfreveal) which showed us the differences in the nested json values (which are additionally marked as sensitive).

But with this recent change, I feel like we are in a dead end.

At some point I read something about a setting, which would allow to disable the new behavior for secrets. Do you have any information about this and how we could enable this in our Elasticsearch instance on Elastic Cloud?

**Comment by breml** [comment] 2024-09-02 11:52
@Kushmaro , @kpollich I would appreciate a short update on this issue after your internal sync. Thanks.

**Comment by breml** [comment] 2024-09-06 07:23
Hi @kpollich 

Thanks for the insights you shared in your post above. I understand the underlying need to better protect the secrets, that are stored within Elasticsearch. 
That being said, the whole situation is very unfortunate for us. We invested significantly in managing our Elastic Stack infrastructure with Terraform. Now we learn, that this is an afterthought for Elastic and it might break at any time, to the extend, where one is forced to lock down versions, basically leading to a situation, where one can no longer update Elasticsearch and Kibana. This is pretty problematic in my opinion and I am now really unsure, how I can sell / explain this to my managers.

Having a situation, where one half of the setup is handled as Iaas (configured with Terraform) and the other half is done manually basically renders the whole Iaas approach useless, since the setup will still be manual and error prone and it can not be automated with CI/CD systems, since there are manual steps involved.

Above, you mentioned the API call `PUT /api/fleet/package_policies/:id`. Is this API documented somewhere?

**Comment by daemitus** [comment] 2024-09-11 17:03
One solution to this is to migrate this resource to the framework from sdk-v2, and use the privatestate.ProviderData to store a map of var/key to secretRef. Then when doing a read, iterate the vars and replace anything that has a stored ref.  Should work in theory, I haven't had the time to fully test out the bit I've been working on though.

**Comment by daemitus** [comment] 2024-09-26 20:45
I'm pretty sure I've got a working solution for this, its tentative on getting in #785 , otherwise I'm going to have to play whack-a-mole on some changes again. I'll open up a draft if you'd like to get some early eyes on it.

**Comment by breml** [comment] 2024-09-27 07:03
Hi @kpollich 
Thanks for coming back to me and providing the additional context.

> > Above, you mentioned the API call PUT /api/fleet/package_policies/:id. Is this API documented somewhere?
> 
> The API is documented here: https://www.elastic.co/docs/api/doc/kibana/operation/operation-get-package-policies. These are sourced from an OpenAPI spec available here: https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/common/openapi/bundled.yaml.

The way I understand the above mentioned API, this is the one, that is used by Kibana and therefore it does not provide a way to get the secrets back. This is the whole goal of the new design described in [secrets.md](https://github.com/elastic/kibana/blob/08f0ed0168aa41179d2d5d31d4243b1b06b161ab/x-pack/plugins/fleet/dev_docs/secrets.md). That being said, in the architecture diagram (in secrets.md) there also exists the Fleet Server, which actually does read the secrets and adds them to the agent policy, which is sent to the agent. So in order to be able to create some sort of workaround with scripting, we would need to be able to access a respective API on the Fleet Server to get the plain text secrets. I don't know, if such an API does even exist, but from my understanding, the Fleet API in Kibana is of no help.

> In short, the team that develops Fleet has no knowledge or insight into Elastic's terraform provider. Describing it as an afterthought is perhaps a little harsh, but probably fair at least as it relates to the Fleet team itself, which is made up of primarily JavaScript engineers working in Kibana.

I apologize for having been harsh. This came out of frustration about the situation and basically being help- and clueless on how to move forward.

> We'll continue to discuss our options for getting a change into the provider to work with the Fleet policy secrets, and in the meantime we are absolutely open to ideas or proofs of concept from the community like [@daemitus](https://github.com/daemitus) has suggested above.

I looked into @daemitus solution today and I feel, this approach is promising. Basically the plain text secret as well as the ID of the secret ref are stored in the private data of the Terraform state, which allows to translate back an forth between the two representations as needed within Terraform. This sound good to me.

I have several questions about this approach:

* @kpollich: My observation is, that with updates for Fleet integrations, often the policies are updated as well. Can you confirm, that in these cases, the ID of the secrets are maintained (stay untouched)? This is very important for the approach of @daemitus to work, since this approach maintains the link between the plain text secret and the ID of the secret reference on the client side (in Terraform) and therefore this ID must not be changed, if the value of the secret is not changed.
* @kpollich: How does this behave, if a manual update of the fleet policy configuration (without changing the secrets) is performed in Kibana, are the ID of the secret values maintained in this case?
* @daemitus: Since we now already have a Terraform configuration used to maintain the Fleet integrations and we therefore also already have a Terraform state (but without the link information in the private prorvider data in the Terraform state), I wonder about the update of the provider and the necessary "migration" of the information in the state. Have you already thought about that scenario as well?

**Comment by Kushmaro** [comment] 2024-09-27 13:33
@kpollich , both @tobio and @dimuon might be able to help review, I hope.

**Closed** 2024-10-01 11:29 UTC
Labels: bug

**Comment by breml** [comment] 2024-10-18 11:51
**Thank you all** (@daemitus, @tobio, @kpollich) for looking into this issue and providing a fix, even though, we have not yet been able to really test and use the new functionality, since we are affected by #820.
