### ISSUE TITLE
include_global_state setting being ignored in creation of SLM

### ISSUE THREAD

**Issue by kevn-gonz** [elastic/terraform-provider-elasticstack#281] opened 2023-02-23 15:59 UTC
Hi guys, I'm trying to create a Snapshot Lifecycle Policy but I noticed the settings I put for "include_global_state" are not considered, it just keeps the default value (true).
Here's my resource config:
```
resource "elasticstack_elasticsearch_snapshot_lifecycle" "slm_policy" {
  name = "my_slm_policy"

  schedule      = "0 0 0 1 * ?"
  snapshot_name = "<daily-snap-{now/d}>"
  repository    = "my_s3_repo"

  indices              = ["data-*", "test-*"]
  ignore_unavailable   = false
  include_global_state = false

  expire_after = "365d"
}
```
As you can see, I am specifying to not include the cluster global state but it is just being ignored. Could you help me figure out if it is only me or you have the same behavior? Thank you!

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.5.0"
    }
  }
}
```

```
Terraform v1.5.0-dev
on windows_amd64
+ provider registry.terraform.io/elastic/elasticstack v0.5.0
```

**Comment by tobio** [comment] 2023-02-23 21:54
Duplicate of https://github.com/elastic/terraform-provider-elasticstack/issues/109

@kevn-gonz this has been fixed in master and will go out in the next release which should be in the next few weeks.

**Closed by tobio** 2023-02-23 21:54 UTC
Labels: bug

**Comment by kevn-gonz** [comment] 2023-03-07 21:56
@tobio thank you
